export const AnalysisData = [
  {
    id: 0,
    name: '옥자',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'happy',
  },
  {
    id: 1,
    name: '옥자',
    date: '2022/02/22',
    isLiked: false,
    emotion: 'happy',
  },
  {
    id: 2,
    name: 'lulu',
    date: '2022/02/22',
    isLiked: false,
    emotion: 'happy',
  },
  {
    id: 3,
    name: '옥자',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'sad',
  },
  {
    id: 4,
    name: '옥자',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'sad',
  },
  {
    id: 5,
    name: '옥자',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'scared',
  },
  {
    id: 6,
    name: 'lulu',
    date: '2022/02/22',
    isLiked: false,
    emotion: 'angry',
  },
  {
    id: 7,
    name: '옥자',
    date: '2022/02/22',
    isLiked: false,
    emotion: 'angry',
  },
  {
    id: 8,
    name: 'lulu',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'angry',
  },
  {
    id: 9,
    name: 'lulu',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'angry',
  },
  {
    id: 10,
    name: 'lulu',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'happy',
  },
  {
    id: 11,
    name: '옥자',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'happy',
  },
  {
    id: 12,
    name: '옥자',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'angry',
  },
  {
    id: 13,
    name: '옥자',
    date: '2022/02/22',
    isLiked: true,
    emotion: 'happy',
  },
];

export default AnalysisData;
