import { baseImg, clickedImg } from '../../common/components/MyPetimage';

const screenwidth =
  window.innerWidth > 0 ? window.innerWidth : window.screen.width;
const isTablet = screenwidth > 767;

const RADIUS = 35;
const CLICKED_RADIUS = isTablet ? 40 : 35;

// 870 x 350
// 400 x 400
const MyPetKeywordsData = [
  {
    x: isTablet ? 770 : 300,
    y: 20,
    keyword: '개쫄보',
    img: baseImg.개쫄보,
    clickedImg: clickedImg.on개쫄보,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 700 : 200,
    y: 70,
    keyword: '게으름',
    img: baseImg.게으름,
    clickedImg: clickedImg.on게으름,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 80,
    y: 120,
    keyword: '관종',
    img: baseImg.관종,
    clickedImg: clickedImg.on관종,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 620 : 200,
    y: 200,
    keyword: '난폭',
    img: baseImg.난폭,
    clickedImg: clickedImg.on난폭,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 680 : 100,
    y: 70,
    keyword: '다소난폭',
    img: baseImg.다소난폭,
    clickedImg: clickedImg.on다소난폭,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 700 : 100,
    y: 220,
    keyword: '도도함',
    img: baseImg.도도함,
    clickedImg: clickedImg.on도도함,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 130,
    y: 270,
    keyword: '똑똑',
    img: baseImg.똑똑,
    clickedImg: clickedImg.on똑똑,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 200,
    y: 280,
    keyword: '반려인바라기',
    img: baseImg.반려인바라기,
    clickedImg: clickedImg.on반려인바라기,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 150,
    y: 220,
    keyword: '사나움',
    img: baseImg.사나움,
    clickedImg: clickedImg.on사나움,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 200,
    y: 250,
    keyword: '시끄러움',
    img: baseImg.시끄러움,
    clickedImg: clickedImg.on시끄러움,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 300,
    y: 260,
    keyword: '신중함',
    img: baseImg.신중함,
    clickedImg: clickedImg.on신중함,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 400 : 100,
    y: 110,
    keyword: '야무짐',
    img: baseImg.야무짐,
    clickedImg: clickedImg.on야무짐,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 300 : 50,
    y: 125,
    keyword: '얌전',
    img: baseImg.얌전,
    clickedImg: clickedImg.on얌전,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 80,
    y: 180,
    keyword: '유순함',
    img: baseImg.유순함,
    clickedImg: clickedImg.on유순함,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 60,
    y: 120,
    keyword: '이중인격',
    img: baseImg.이중인격,
    clickedImg: clickedImg.on이중인격,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 450 : 250,
    y: 70,
    keyword: '자신감 많음',
    img: baseImg.자신감많음,
    clickedImg: clickedImg.on자신감많음,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 460 : 80,
    y: 150,
    keyword: '잘짖음',
    img: baseImg.잘짖음,
    clickedImg: clickedImg.on잘짖음,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 550 : 300,
    y: 150,
    keyword: '장난 심함',
    img: baseImg.장난심함,
    clickedImg: clickedImg.on장난심함,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 500 : 100,
    y: 100,
    keyword: '애교많음',
    img: baseImg.애교많음,
    clickedImg: clickedImg.on애교많음,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 670 : 180,
    y: 120,
    keyword: '조심스러움',
    img: baseImg.조심스러움,
    clickedImg: clickedImg.on조심스러움,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 600 : 200,
    y: 220,
    keyword: '집 잘 지킴',
    img: baseImg.집잘지킴,
    clickedImg: clickedImg.on집잘지킴,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 550 : 50,
    y: isTablet ? 185 : 50,
    keyword: '쫄보',
    img: baseImg.쫄보,
    clickedImg: clickedImg.on쫄보,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 430 : 50,
    y: isTablet ? 180 : 100,
    keyword: '착함',
    img: baseImg.착함,
    clickedImg: clickedImg.on착함,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 500 : 50,
    y: 165,
    keyword: '충성심 폭발',
    img: baseImg.충성심폭발,
    clickedImg: clickedImg.on충성심폭발,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 450 : 70,
    y: 160,
    keyword: '침착',
    img: baseImg.침착,
    clickedImg: clickedImg.on침착,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 550 : 200,
    y: 185,
    keyword: '호기심 강함',
    img: baseImg.호기심강함,
    clickedImg: clickedImg.on호기심강함,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 350,
    y: 105,
    keyword: '활발',
    img: baseImg.활발,
    clickedImg: clickedImg.on활발,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },

  // 빈 공
  {
    x: isTablet ? 10 : 9999,
    y: 20,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 100 : 9999,
    y: 120,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 300 : 9999,
    y: 520,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 400 : 9999,
    y: 20,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 300 : 9999,
    y: 320,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 500 : 9999,
    y: 120,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 700 : 9999,
    y: 50,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 690 : 9999,
    y: 30,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 30 : 9999,
    y: 10,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 40 : 9999,
    y: 130,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
];

export default MyPetKeywordsData;
