import { baseImg, clickedImg } from './Userimage';

const RADIUS = 35;
const CLICKED_RADIUS = 40;
const screenwidth =
  window.innerWidth > 0 ? window.innerWidth : window.screen.width;
const isTablet = screenwidth > 767;
// 870 x 350
// 400 x 400

const UserKeywordsData = [
  {
    x: isTablet ? 770 : 20,
    y: 20,
    keyword: '가족과함께삼',
    img: baseImg.가족과함께삼,
    clickedImg: clickedImg.on가족과함께삼,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 700 : 50,
    y: 70,
    keyword: '데일리운동',
    img: baseImg.데일리운동,
    clickedImg: clickedImg.on데일리운동,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 770 : 50,
    y: 120,
    keyword: '디지털노마드',
    img: baseImg.디지털노마드,
    clickedImg: clickedImg.on디지털노마드,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 620 : 200,
    y: 200,
    keyword: '산책',
    img: baseImg.산책,
    clickedImg: clickedImg.on산책,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 680 : 150,
    y: 70,
    keyword: '새벽피트니스',
    img: baseImg.새벽피트니스,
    clickedImg: clickedImg.on새벽피트니스,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 700 : 20,
    y: 220,
    keyword: '소확행',
    img: baseImg.소확행,
    clickedImg: clickedImg.on소확행,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 130,
    y: 270,
    keyword: '싱글',
    img: baseImg.싱글,
    clickedImg: clickedImg.on싱글,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 200,
    y: 280,
    keyword: '썸타는중',
    img: baseImg.썸타는중,
    clickedImg: clickedImg.on썸타는중,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 150,
    y: 220,
    keyword: '야근',
    img: baseImg.야근,
    clickedImg: clickedImg.on야근,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 200,
    y: 250,
    keyword: '욜로',
    img: baseImg.욜로,
    clickedImg: clickedImg.on욜로,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 300,
    y: 260,
    keyword: '워라벨추구',
    img: baseImg.워라벨추구,
    clickedImg: clickedImg.on워라벨추구,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 400,
    y: 210,
    keyword: '육아',
    img: baseImg.육아,
    clickedImg: clickedImg.on육아,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 300 : 250,
    y: isTablet ? 225 : 200,
    keyword: '일인가구',
    img: baseImg.일인가구,
    clickedImg: clickedImg.on일인가구,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 80,
    y: 180,
    keyword: '취준생',
    img: baseImg.취준생,
    clickedImg: clickedImg.on취준생,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 60,
    y: 120,
    keyword: '커플',
    img: baseImg.커플,
    clickedImg: clickedImg.on커플,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 450 : 350,
    y: 70,
    keyword: '퇴근길러닝',
    img: baseImg.퇴근길러닝,
    clickedImg: clickedImg.on퇴근길러닝,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 460 : 200,
    y: 150,
    keyword: '혼술',
    img: baseImg.혼술,
    clickedImg: clickedImg.on혼술,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: isTablet ? 550 : 200,
    y: 150,
    keyword: '혼카페',
    img: baseImg.혼카페,
    clickedImg: clickedImg.on혼카페,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },

  // 빈 공
  {
    x: 10,
    y: 20,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 100,
    y: 120,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 300,
    y: 520,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 400,
    y: 20,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 300,
    y: 320,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 500,
    y: 120,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 700,
    y: 50,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 690,
    y: 30,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 30,
    y: 10,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
  {
    x: 760,
    y: 130,
    keyword: '빈공',
    img: baseImg.base,
    clickedImg: clickedImg.clickedBase,
    radius: RADIUS,
    clickedRadius: CLICKED_RADIUS,
    isClicked: false,
  },
];

export default UserKeywordsData;
